"""
Tally Prime export for invoices generated by this app.

Builds (a) an import-ready Tally XML file and (b) an Excel sheet from the same
invoice figures the PDF uses (see invoice.py), so Tally always matches the
printed invoice: prices are GST-inclusive, 18% IGST, plus delivery charge.

Amount-only sales vouchers (no stock items). Each invoice becomes:
    Dr  <customer ledger>          grand total
    Cr  Sales                      taxable value
    Cr  Output IGST 18%            IGST
    Cr  Delivery Charges           delivery (if any)
    +/- Round Off                  only if the paise don't add up

The customer ledger is named by the customer's 10-digit mobile number (same
number always -> same ledger), with the real name as the mailing name. The XML
also carries the ledger masters, so Tally creates missing ledgers on import.

Ledger names are configurable through environment variables so they can match
the target Tally company exactly.
"""

import os
import re
from datetime import datetime
from xml.sax.saxutils import escape

from invoice import GST_RATE, gst_state_code

SALES_LEDGER = os.environ.get("TALLY_SALES_LEDGER", "Sales")
IGST_LEDGER = os.environ.get("TALLY_IGST_LEDGER", "Output IGST 18%")
DELIVERY_LEDGER = os.environ.get("TALLY_DELIVERY_LEDGER", "Delivery Charges")
ROUNDOFF_LEDGER = os.environ.get("TALLY_ROUNDOFF_LEDGER", "Round Off")
VOUCHER_TYPE = os.environ.get("TALLY_VOUCHER_TYPE", "Sales")
DEFAULT_COMPANY = os.environ.get("TALLY_COMPANY_NAME", "")
UOM = os.environ.get("TALLY_UOM", "nos")  # unit of measure shown against each item's qty/rate

# Tally's own spelling for the few states that differ from common usage.
_TALLY_STATE_NAMES = {
    "jammu and kashmir": "Jammu & Kashmir",
    "jammu & kashmir": "Jammu & Kashmir",
    "andaman and nicobar islands": "Andaman & Nicobar Islands",
    "dadra and nagar haveli and daman and diu": "Dadra & Nagar Haveli and Daman & Diu",
    "orissa": "Odisha",
    "pondicherry": "Puducherry",
    "new delhi": "Delhi",
}

_BAD_XML_CHARS = re.compile(r"[\x00-\x08\x0b\x0c\x0e-\x1f]")


# ---------------------------------------------------------------------------
# Small helpers
# ---------------------------------------------------------------------------

def x(text):
    """XML-escape text (and drop control characters Tally rejects)."""
    return escape(_BAD_XML_CHARS.sub("", str(text if text is not None else "")))


def amt(n):
    return f"{n:.2f}"


def parse_invoice_date(value):
    """'4-Aug-26' -> datetime. Returns None if it can't be parsed."""
    if not value:
        return None
    try:
        return datetime.strptime(value.strip(), "%d-%b-%y")
    except ValueError:
        return None


def normalize_mobile(phone):
    """Digits only, no +91 / leading 0 -> 10-digit number. '' if unusable."""
    digits = re.sub(r"\D", "", phone or "")
    if len(digits) > 10 and digits.startswith("91"):
        digits = digits[2:]
    digits = digits.lstrip("0") if len(digits) > 10 else digits
    if len(digits) > 10:
        digits = digits[-10:]
    return digits if len(digits) == 10 else ""


def party_ledger_name(order):
    mobile = normalize_mobile(order.get("customer_phone"))
    if mobile:
        return mobile
    # No usable number: fall back to the order number so the ledger name is never blank.
    ref = re.sub(r"[^A-Za-z0-9]", "", str(order.get("order_name") or order.get("shopify_order_id") or "NA"))
    return f"ORD{ref}"


def tally_state(state):
    s = (state or "").strip()
    if not s or not gst_state_code(s):
        return ""
    return _TALLY_STATE_NAMES.get(s.lower(), s.title())


def fy_start(dt):
    year = dt.year if dt.month >= 4 else dt.year - 1
    return f"{year}0401"


# ---------------------------------------------------------------------------
# Figures — mirrors build_invoice_pdf() so Tally matches the printed invoice
# ---------------------------------------------------------------------------

def compute_invoice(order, items):
    total_incl = 0.0
    total_base = 0.0
    lines = []
    item_entries = []
    for it in items:
        qty = int(it.get("quantity") or 1)
        unit_incl = float(it.get("price") or 0)
        line_incl = unit_incl * qty
        total_incl += line_incl
        title = it.get("title") or ""
        variant = it.get("variant_title") or ""
        name = (title + " " + variant).strip() or "Item"
        lines.append(f"{name} x{qty}")

        # Per-item taxable (GST-exclusive) rate and amount. Tally recomputes each
        # stock line as Rate x Qty on import rather than trusting our AMOUNT tag,
        # so rate must be rounded FIRST and amount derived from that rounded rate
        # (never rounded independently) or the two can differ by a paisa and Tally
        # rejects the voucher with "Mismatch in total amount between Credit and
        # Debit entries."
        line_base_raw = line_incl / (1 + GST_RATE)
        rate = round(line_base_raw / qty, 2) if qty else 0.0
        line_base = round(rate * qty, 2)
        total_base += line_base
        item_entries.append({"name": name, "qty": qty, "rate": rate, "amount": line_base})

    total_base = round(total_base, 2)
    igst = round(total_base * GST_RATE, 2)
    sales = total_base
    delivery = round(float(order.get("shipping_amount") or 0), 2)
    grand_total = round(total_incl + delivery, 2)
    round_off = round(grand_total - (sales + igst + delivery), 2)
    return {
        "sales": sales,
        "igst": igst,
        "delivery": delivery,
        "round_off": round_off,
        "grand_total": grand_total,
        "lines": lines,
        "items": item_entries,
    }


def build_records(invoices):
    """invoices: list of (order_dict, items_list, payment_type). Returns list of dicts."""
    records = []
    for order, items, payment_type in invoices:
        dt = parse_invoice_date(order.get("invoice_date")) or datetime.now()
        fig = compute_invoice(order, items)
        addr_parts = [order.get("shipping_address1"), order.get("shipping_address2"), order.get("shipping_city")]
        records.append(
            {
                "order": order,
                "dt": dt,
                "invoice_number": order.get("invoice_number"),
                "order_name": order.get("order_name") or "",
                "ledger": party_ledger_name(order),
                "customer_name": (order.get("customer_name") or "").strip(),
                "address_lines": [p.strip() for p in addr_parts if p and p.strip()],
                "state": tally_state(order.get("shipping_state")),
                "pincode": (order.get("shipping_pincode") or "").strip(),
                "payment_type": (payment_type or "prepaid").upper(),
                **fig,
            }
        )
    return records


# ---------------------------------------------------------------------------
# XML
# ---------------------------------------------------------------------------

def _ledger_master(name, parent, extra=""):
    return (
        '<TALLYMESSAGE xmlns:UDF="TallyUDF">'
        f'<LEDGER NAME="{x(name)}">'
        f"<NAME.LIST><NAME>{x(name)}</NAME></NAME.LIST>"
        f"<PARENT>{x(parent)}</PARENT>"
        f"{extra}"
        "</LEDGER></TALLYMESSAGE>"
    )


def _unit_master(unit):
    return (
        '<TALLYMESSAGE xmlns:UDF="TallyUDF">'
        f'<UNIT NAME="{x(unit)}" ACTION="Create">'
        f"<NAME>{x(unit)}</NAME>"
        "<ISSIMPLEUNIT>Yes</ISSIMPLEUNIT>"
        "</UNIT></TALLYMESSAGE>"
    )


def _stock_item_master(name, unit):
    return (
        '<TALLYMESSAGE xmlns:UDF="TallyUDF">'
        f'<STOCKITEM NAME="{x(name)}" ACTION="Create">'
        f"<NAME.LIST><NAME>{x(name)}</NAME></NAME.LIST>"
        f"<BASEUNITS>{x(unit)}</BASEUNITS>"
        "</STOCKITEM></TALLYMESSAGE>"
    )


def _customer_master(rec):
    since = fy_start(rec["dt"])
    addr = "".join(f"<ADDRESS>{x(a)}</ADDRESS>" for a in rec["address_lines"])
    state = f"<STATE>{x(rec['state'])}</STATE>" if rec["state"] else ""
    pos = f"<PLACEOFSUPPLY>{x(rec['state'])}</PLACEOFSUPPLY>" if rec["state"] else ""
    led_state = f"<LEDSTATENAME>{x(rec['state'])}</LEDSTATENAME>" if rec["state"] else ""
    extra = (
        "<LEDMAILINGDETAILS.LIST>"
        f'<ADDRESS.LIST TYPE="String">{addr}</ADDRESS.LIST>'
        f"<APPLICABLEFROM>{since}</APPLICABLEFROM>"
        f"<PINCODE>{x(rec['pincode'])}</PINCODE>"
        f"<MAILINGNAME>{x(rec['customer_name'])}</MAILINGNAME>"
        f"{state}<COUNTRY>India</COUNTRY>"
        "</LEDMAILINGDETAILS.LIST>"
        "<LEDGSTREGDETAILS.LIST>"
        f"<APPLICABLEFROM>{since}</APPLICABLEFROM>"
        "<GSTREGISTRATIONTYPE>Unregistered/Consumer</GSTREGISTRATIONTYPE>"
        f"{pos}"
        "</LEDGSTREGDETAILS.LIST>"
        "<COUNTRYNAME>India</COUNTRYNAME>"
        f"{led_state}"
        "<ISBILLWISEON>No</ISBILLWISEON>"
    )
    return _ledger_master(rec["ledger"], "Sundry Debtors", extra)


def _entry(name, amount, party=False):
    """Credit entries carry a positive amount; the party (debit) carries a negative one."""
    deemed = "Yes" if amount < 0 else "No"
    return (
        "<ALLLEDGERENTRIES.LIST>"
        f"<LEDGERNAME>{x(name)}</LEDGERNAME>"
        f"<ISDEEMEDPOSITIVE>{deemed}</ISDEEMEDPOSITIVE>"
        f"<ISPARTYLEDGER>{'Yes' if party else 'No'}</ISPARTYLEDGER>"
        f"<AMOUNT>{amt(amount)}</AMOUNT>"
        "</ALLLEDGERENTRIES.LIST>"
    )


def _inventory_entry(item):
    """One stock-item line (Name of Item / Qty / Rate / Amount), allocated to Sales."""
    qty_unit = f"{item['qty']} {UOM}"
    return (
        "<ALLINVENTORYENTRIES.LIST>"
        f"<STOCKITEMNAME>{x(item['name'])}</STOCKITEMNAME>"
        "<ISDEEMEDPOSITIVE>No</ISDEEMEDPOSITIVE>"
        f"<RATE>{amt(item['rate'])}/{x(UOM)}</RATE>"
        f"<AMOUNT>{amt(item['amount'])}</AMOUNT>"
        f"<ACTUALQTY>{x(qty_unit)}</ACTUALQTY>"
        f"<BILLEDQTY>{x(qty_unit)}</BILLEDQTY>"
        "<ACCOUNTINGALLOCATIONS.LIST>"
        f"<LEDGERNAME>{x(SALES_LEDGER)}</LEDGERNAME>"
        "<ISDEEMEDPOSITIVE>No</ISDEEMEDPOSITIVE>"
        f"<AMOUNT>{amt(item['amount'])}</AMOUNT>"
        "</ACCOUNTINGALLOCATIONS.LIST>"
        "</ALLINVENTORYENTRIES.LIST>"
    )


def _voucher(rec):
    date = rec["dt"].strftime("%Y%m%d")
    narration = f"Order {rec['order_name']} | {rec['payment_type']} | " + "; ".join(rec["lines"])
    addr = "".join(f"<BASICBUYERADDRESS>{x(a)}</BASICBUYERADDRESS>" for a in rec["address_lines"])
    state = x(rec["state"])
    state_tags = ""
    if rec["state"]:
        state_tags = (
            f"<STATENAME>{state}</STATENAME>"
            f"<PLACEOFSUPPLY>{state}</PLACEOFSUPPLY>"
            f"<CONSIGNEESTATENAME>{state}</CONSIGNEESTATENAME>"
        )

    # Party/GST/Delivery/Round-off stay as plain ledger entries; each stock item's
    # own share of the taxable value is allocated inside its ALLINVENTORYENTRIES
    # block instead of a single lump "Sales" line.
    entries = [_entry(rec["ledger"], -rec["grand_total"], party=True)]
    if rec["igst"]:
        entries.append(_entry(IGST_LEDGER, rec["igst"]))
    if rec["delivery"]:
        entries.append(_entry(DELIVERY_LEDGER, rec["delivery"]))
    if rec["round_off"]:
        entries.append(_entry(ROUNDOFF_LEDGER, rec["round_off"]))

    inv_entries = [_inventory_entry(it) for it in rec["items"]]

    return (
        '<TALLYMESSAGE xmlns:UDF="TallyUDF">'
        f'<VOUCHER VCHTYPE="{x(VOUCHER_TYPE)}" ACTION="Create" OBJVIEW="Invoice Voucher View">'
        f"<DATE>{date}</DATE>"
        f"<EFFECTIVEDATE>{date}</EFFECTIVEDATE>"
        f"<VOUCHERTYPENAME>{x(VOUCHER_TYPE)}</VOUCHERTYPENAME>"
        f"<VOUCHERNUMBER>{x(rec['invoice_number'])}</VOUCHERNUMBER>"
        f"<REFERENCE>{x(rec['order_name'])}</REFERENCE>"
        f"<PARTYLEDGERNAME>{x(rec['ledger'])}</PARTYLEDGERNAME>"
        f"<PARTYNAME>{x(rec['ledger'])}</PARTYNAME>"
        f"<BASICBUYERNAME>{x(rec['customer_name'])}</BASICBUYERNAME>"
        f"<PARTYMAILINGNAME>{x(rec['customer_name'])}</PARTYMAILINGNAME>"
        f'<BASICBUYERADDRESS.LIST TYPE="String">{addr}</BASICBUYERADDRESS.LIST>'
        f"{state_tags}"
        "<COUNTRYOFRESIDENCE>India</COUNTRYOFRESIDENCE>"
        "<GSTREGISTRATIONTYPE>Unregistered/Consumer</GSTREGISTRATIONTYPE>"
        "<ISINVOICE>Yes</ISINVOICE>"
        "<PERSISTEDVIEW>Invoice Voucher View</PERSISTEDVIEW>"
        f"<NARRATION>{x(narration[:1000])}</NARRATION>"
        + "".join(inv_entries)
        + "".join(entries)
        + "</VOUCHER></TALLYMESSAGE>"
    )


def build_tally_xml(records, company=""):
    company = company or DEFAULT_COMPANY
    company_tag = f"<SVCURRENTCOMPANY>{x(company)}</SVCURRENTCOMPANY>" if company else ""

    masters = [
        _unit_master(UOM),
        _ledger_master(SALES_LEDGER, "Sales Accounts"),
        _ledger_master(
            IGST_LEDGER,
            "Duties & Taxes",
            "<TAXTYPE>GST</TAXTYPE><GSTDUTYHEAD>Integrated Tax</GSTDUTYHEAD>"
            f"<RATEOFTAXCALCULATION>{int(GST_RATE * 100)}</RATEOFTAXCALCULATION>",
        ),
    ]
    if any(r["delivery"] for r in records):
        masters.append(_ledger_master(DELIVERY_LEDGER, "Sales Accounts"))
    if any(r["round_off"] for r in records):
        masters.append(_ledger_master(ROUNDOFF_LEDGER, "Indirect Expenses"))

    seen_items = set()
    for rec in records:
        for it in rec["items"]:
            if it["name"] not in seen_items:
                seen_items.add(it["name"])
                masters.append(_stock_item_master(it["name"], UOM))

    seen = set()
    for rec in records:
        if rec["ledger"] not in seen:
            seen.add(rec["ledger"])
            masters.append(_customer_master(rec))

    vouchers = [_voucher(r) for r in records]

    return (
        '<?xml version="1.0" encoding="UTF-8"?>'
        "<ENVELOPE>"
        "<HEADER><TALLYREQUEST>Import Data</TALLYREQUEST></HEADER>"
        "<BODY><IMPORTDATA>"
        "<REQUESTDESC><REPORTNAME>Vouchers</REPORTNAME>"
        f"<STATICVARIABLES>{company_tag}</STATICVARIABLES></REQUESTDESC>"
        "<REQUESTDATA>" + "".join(masters) + "".join(vouchers) + "</REQUESTDATA>"
        "</IMPORTDATA></BODY></ENVELOPE>"
    )


# ---------------------------------------------------------------------------
# Excel
# ---------------------------------------------------------------------------

EXCEL_HEADERS = [
    "Voucher Type", "Invoice Number", "Invoice Date", "Order ID", "Customer Ledger (Mobile)",
    "Customer Name", "Address", "City", "State", "Pincode", "Payment Type", "Items",
    "Sales (Taxable)", f"IGST {int(GST_RATE * 100)}%", "Delivery Charge", "Round Off", "Invoice Total",
]


def excel_rows(records):
    rows = []
    for r in records:
        o = r["order"]
        addr = ", ".join(p for p in [o.get("shipping_address1"), o.get("shipping_address2")] if p)
        rows.append(
            [
                VOUCHER_TYPE, r["invoice_number"], r["dt"].strftime("%d-%m-%Y"), r["order_name"], r["ledger"],
                r["customer_name"], addr, o.get("shipping_city") or "", r["state"], r["pincode"],
                r["payment_type"], "; ".join(r["lines"]),
                r["sales"], r["igst"], r["delivery"], r["round_off"], r["grand_total"],
            ]
        )
    return rows
